### ISSUE TITLE
Installable image built by GitHub actions 

### ISSUE THREAD

**Issue by ThePrez** [ThePrez/Manzan#46]

**Comment by jonnyz32** [comment]
@ThePrez  Can we close this? We can aleady build the installer using [https://github.com/ThePrez/Manzan/blob/main/.github/workflows/build_release.yml](https://github.com/ThePrez/Manzan/blob/main/.github/workflows/build_release.yml)

**Comment by ThePrez** [comment]
@jonnyz32 yes, makes sense. Thanks!
